# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='product_id',
            new_name='product',
        ),
    ]
