# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0002_auto_20180312_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='product',
        ),
    ]
