# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0003_remove_process_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailywork.Process'),
        ),
    ]
