# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0004_products_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='process',
        ),
        migrations.AddField(
            model_name='process',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailywork.Products'),
        ),
    ]
