# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0005_auto_20180313_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_code',
            field=models.CharField(max_length=16, null=True, verbose_name='\u5de5\u5e8f\u4ee3\u7801'),
        ),
    ]
