# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0007_auto_20180313_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_name',
            field=models.CharField(max_length=128, verbose_name='\u5de5\u5e8f\u540d'),
        ),
    ]
