# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0008_auto_20180313_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_code',
            field=models.CharField(help_text='\u8bf7\u8f93\u5165\u5de5\u5e8f\u4ee3\u7801\uff1a', max_length=16, null=True, verbose_name='\u5de5\u5e8f\u4ee3\u7801'),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_name',
            field=models.CharField(help_text='\u8bf7\u8f93\u5165\u5de5\u5e8f\u540d\uff1a', max_length=128, verbose_name='\u5de5\u5e8f\u540d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='deliver_date',
            field=models.DateField(help_text='\u8bf7\u8f93\u5165\u4ea4\u8d27\u65e5\u671f\uff1a', max_length=8, verbose_name='\u4ea4\u8d27\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='products',
            name='order_num',
            field=models.IntegerField(help_text='\u8bf7\u8f93\u5165\u8ba2\u5355\u6570\u91cf\uff1a', verbose_name='\u8ba2\u5355\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.CharField(help_text='\u8bf7\u8f93\u5165\u4ea7\u54c1\u6807\u8bc6\uff1a', max_length=8, primary_key=True, serialize=False, verbose_name='\u4ea7\u54c1ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(help_text='\u8bf7\u8f93\u5165\u4ea7\u54c1\u540d\uff1a', max_length=128, unique=True, verbose_name='\u4ea7\u54c1\u540d'),
        ),
    ]
