# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0010_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_num', models.IntegerField(help_text='\u8bf7\u8f93\u5165\u5b9a\u989d\u6570\u91cf\uff1a', verbose_name='\u5b9a\u989d\u6570\u91cf')),
                ('operater', models.CharField(help_text='\u8bf7\u8f93\u5165\u4f5c\u4e1a\u4eba\u5458\uff1a', max_length=16, verbose_name='\u4f5c\u4e1a\u5458')),
                ('produce_num', models.IntegerField(help_text='\u8bf7\u8f93\u5165\u751f\u4ea7\u6570\u91cf\uff1a', verbose_name='\u751f\u4ea7\u6570\u91cf')),
                ('process_des', models.TextField(help_text='\u8bf7\u8f93\u5165\u4f5c\u4e1a\u8981\u70b9\u6307\u5bfc\uff1a', verbose_name='\u4f5c\u4e1a\u8981\u70b9\u6307\u5bfc')),
                ('detect_log', models.TextField(help_text='\u8bf7\u8f93\u5165\u9996\u68c0\u8bb0\u5f55\uff1a', verbose_name='\u9996\u68c0\u8bb0\u5f55')),
                ('inspect_log', models.TextField(help_text='\u8bf7\u8f93\u5165\u5de1\u68c0\u8bb0\u5f55\uff1a', verbose_name='\u5de1\u68c0\u8bb0\u5f55')),
                ('inspect_date', models.DateField(help_text='\u8bf7\u8f93\u5165\u65e5\u671f\uff1a', max_length=8, verbose_name='\u65e5\u671f')),
                ('inspector', models.CharField(help_text='\u8bf7\u8f93\u5165\u5de1\u68c0\u5458\uff1a', max_length=16, verbose_name='\u5de1\u68c0\u5458')),
                ('description', models.TextField(help_text='\u8bf7\u8f93\u5165\u5907\u6ce8\uff1a', verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='\u8bf7\u8f93\u5165\u6750\u6599\u540d\uff1a', max_length=128, unique=True, verbose_name='\u6750\u6599\u540d')),
                ('material_code', models.CharField(help_text='\u8bf7\u8f93\u5165\u6750\u6599\u89c4\u683c\uff1a', max_length=128, verbose_name='\u6750\u6599\u89c4\u683c')),
                ('inventory_num', models.IntegerField(help_text='\u8bf7\u8f93\u5165\u5e93\u5b58\u6570\u91cf\uff1a', verbose_name='\u5e93\u5b58\u6570\u91cf')),
                ('used_num', models.IntegerField(help_text='\u8bf7\u8f93\u5165\u5df2\u7528\u6570\u91cf\uff1a', verbose_name='\u5df2\u7528\u6570\u91cf')),
            ],
        ),
        migrations.AddField(
            model_name='main',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailywork.Material'),
        ),
        migrations.AddField(
            model_name='main',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailywork.Process'),
        ),
        migrations.AddField(
            model_name='main',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailywork.Products'),
        ),
    ]
