# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-25 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0011_auto_20180325_2203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='Produce',
        ),
    ]
