# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0012_auto_20180325_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='inventory_num',
            field=models.IntegerField(help_text='\u8bf7\u8f93\u5165\u5e93\u5b58\u6570\u91cf\uff1a', null=True, verbose_name='\u5e93\u5b58\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_code',
            field=models.CharField(help_text='\u8bf7\u8f93\u5165\u6750\u6599\u89c4\u683c\uff1a', max_length=128, null=True, verbose_name='\u6750\u6599\u89c4\u683c'),
        ),
        migrations.AlterField(
            model_name='material',
            name='used_num',
            field=models.IntegerField(help_text='\u8bf7\u8f93\u5165\u5df2\u7528\u6570\u91cf\uff1a', null=True, verbose_name='\u5df2\u7528\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='assigned_num',
            field=models.IntegerField(help_text='\u8bf7\u8f93\u5165\u5b9a\u989d\u6570\u91cf\uff1a', null=True, verbose_name='\u5b9a\u989d\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='description',
            field=models.TextField(help_text='\u8bf7\u8f93\u5165\u5907\u6ce8\uff1a', null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='detect_log',
            field=models.TextField(help_text='\u8bf7\u8f93\u5165\u9996\u68c0\u8bb0\u5f55\uff1a', null=True, verbose_name='\u9996\u68c0\u8bb0\u5f55'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='inspect_date',
            field=models.DateField(help_text='\u8bf7\u8f93\u5165\u65e5\u671f\uff1a', max_length=8, null=True, verbose_name='\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='inspect_log',
            field=models.TextField(help_text='\u8bf7\u8f93\u5165\u5de1\u68c0\u8bb0\u5f55\uff1a', null=True, verbose_name='\u5de1\u68c0\u8bb0\u5f55'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='inspector',
            field=models.CharField(help_text='\u8bf7\u8f93\u5165\u5de1\u68c0\u5458\uff1a', max_length=16, null=True, verbose_name='\u5de1\u68c0\u5458'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='operater',
            field=models.CharField(help_text='\u8bf7\u8f93\u5165\u4f5c\u4e1a\u4eba\u5458\uff1a', max_length=16, null=True, verbose_name='\u4f5c\u4e1a\u5458'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='process_des',
            field=models.TextField(help_text='\u8bf7\u8f93\u5165\u4f5c\u4e1a\u8981\u70b9\u6307\u5bfc\uff1a', null=True, verbose_name='\u4f5c\u4e1a\u8981\u70b9\u6307\u5bfc'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='produce_num',
            field=models.IntegerField(help_text='\u8bf7\u8f93\u5165\u751f\u4ea7\u6570\u91cf\uff1a', null=True, verbose_name='\u751f\u4ea7\u6570\u91cf'),
        ),
    ]
