# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0013_auto_20180326_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produce',
            old_name='operater',
            new_name='operator',
        ),
    ]
