# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0014_auto_20180326_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='inventory_num',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='used_num',
            new_name='used',
        ),
    ]
