# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0015_auto_20180326_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='process_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='process_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='process',
            name='product',
        ),
    ]
