# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-28 09:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0016_auto_20180326_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='\u8bf7\u8f93\u5165\u5458\u5de5\u5de5\u53f7\uff1a', unique=True, verbose_name='\u5de5\u53f7')),
                ('user_name', models.CharField(help_text='\u8bf7\u8f93\u5165\u5458\u5de5\u59d3\u540d\uff1a', max_length=32, verbose_name='\u59d3\u540d')),
                ('is_operator', models.BooleanField(help_text='\u662f\u5426\u62c5\u5f53\u4f5c\u4e1a\u5458\u89d2\u8272\uff1f', verbose_name='\u4f5c\u4e1a\u5458\uff1f')),
                ('is_inspector', models.BooleanField(help_text='\u662f\u5426\u62c5\u5f53\u5de1\u68c0\u5458\u89d2\u8272\uff1f', verbose_name='\u5de1\u68c0\u5458\uff1f')),
                ('description', models.TextField(blank=True, help_text='\u8bf7\u8f93\u5165\u5907\u6ce8\u63cf\u8ff0\uff1a', null=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='inventory',
            field=models.IntegerField(default='0', help_text='\u8bf7\u8f93\u5165\u5e93\u5b58\u6570\u91cf\uff1a', null=True, verbose_name='\u5e93\u5b58\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='material',
            name='used',
            field=models.IntegerField(default='0', help_text='\u8bf7\u8f93\u5165\u5df2\u7528\u6570\u91cf\uff1a', null=True, verbose_name='\u5df2\u7528\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='process',
            name='code',
            field=models.CharField(default='', help_text='\u8bf7\u8f93\u5165\u5de5\u5e8f\u4ee3\u7801\uff1a', max_length=16, null=True, verbose_name='\u5de5\u5e8f\u4ee3\u7801'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='assigned_num',
            field=models.IntegerField(default='0', help_text='\u8bf7\u8f93\u5165\u5b9a\u989d\u6570\u91cf\uff1a', null=True, verbose_name='\u5b9a\u989d\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='description',
            field=models.TextField(blank=True, help_text='\u8bf7\u8f93\u5165\u5907\u6ce8\uff1a', null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='detect_log',
            field=models.TextField(blank=True, help_text='\u8bf7\u8f93\u5165\u9996\u68c0\u8bb0\u5f55\uff1a', null=True, verbose_name='\u9996\u68c0\u8bb0\u5f55'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='inspect_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='\u8bf7\u8f93\u5165\u65e5\u671f\uff1a', max_length=8, verbose_name='\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='inspect_log',
            field=models.TextField(blank=True, help_text='\u8bf7\u8f93\u5165\u5de1\u68c0\u8bb0\u5f55\uff1a', null=True, verbose_name='\u5de1\u68c0\u8bb0\u5f55'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='inspector',
            field=models.CharField(blank=True, help_text='\u8bf7\u8f93\u5165\u5de1\u68c0\u5458\uff1a', max_length=16, null=True, verbose_name='\u5de1\u68c0\u5458'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='material',
            field=models.ForeignKey(blank=True, help_text='\u8bf7\u9009\u62e9\u6750\u6599\u89c4\u683c\uff1a', null=True, on_delete=django.db.models.deletion.CASCADE, to='dailywork.Material'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='process',
            field=models.ForeignKey(blank=True, help_text='\u8bf7\u9009\u62e9\u5de5\u5e8f\uff1a', null=True, on_delete=django.db.models.deletion.CASCADE, to='dailywork.Process'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='process_des',
            field=models.TextField(blank=True, help_text='\u8bf7\u8f93\u5165\u4f5c\u4e1a\u8981\u70b9\u6307\u5bfc\uff1a', null=True, verbose_name='\u4f5c\u4e1a\u8981\u70b9\u6307\u5bfc'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='produce_num',
            field=models.IntegerField(default='0', help_text='\u8bf7\u8f93\u5165\u751f\u4ea7\u6570\u91cf\uff1a', null=True, verbose_name='\u751f\u4ea7\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='products',
            name='deliver_date',
            field=models.DateField(default=datetime.datetime.now, help_text='\u8bf7\u8f93\u5165\u4ea4\u8d27\u65e5\u671f\uff1a', max_length=8, verbose_name='\u4ea4\u8d27\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='products',
            name='order_num',
            field=models.IntegerField(default='0', help_text='\u8bf7\u8f93\u5165\u8ba2\u5355\u6570\u91cf\uff1a', verbose_name='\u8ba2\u5355\u6570\u91cf'),
        ),
    ]
