# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-28 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0017_auto_20180328_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='user_id',
            new_name='worker_id',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='user_name',
            new_name='worker_name',
        ),
    ]
